[package]
name = "word_games"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
rusqlite = "0.31.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
uuid = {version = "1.8.0", features=["v4", "fast-rng"]}
